# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site navigation

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- alembic-jekyll-theme.gemspec

# 2. Installed Gems
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji

# 3. Gem settings
paginate: 2 # jekyll-paginate > items per page
paginate_path: blog/page:num # jekyll-paginate > blog page
jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
twitter:
  username: _lab41 # jekyll-seo-tag > Owners twitter username
author: VishalSandesara# jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: Vishal Sandesara # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://twitter.com/_lab41
    - https://www.facebook.com/voices18
    - https://www.linkedin.com/in/voices18
    - https://plus.google.com/+voices18
    - https://github.com/lab41

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Europe/London # Timezone for blog posts and alike

# 5. Collections
collections:
  posts:
    title: Events # Needed for Siteleaf
    output: true
    description: "Here are upcoming and past events for VOiCES" # The post list page content
    feature_text: |
      ## VOiCES
      Voices Obscured in Complex Environmental Scenarios
    feature_image: "https://picsum.photos/2560/600?image=866"

# 6. Jekyll collections settings
defaults:
  -
    values:
      image: "/assets/default-social-image.png" # Default image for sharing

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
lang: en-GB # Set the site language
title: "VOiCES" # Site name or title, also used in jekyll-seo-tag
logo: "/images/VOiCES_logo.png" # Site logo, also used in jekyll-seo-tag
description: "The Voices Obscured in Complex Environmental Settings (VOiCES) corpus is a creative commons speech dataset targeting acoustically challenging and reverberant environments with robust labels and truth data for transcription, denoising, and speaker identification." # Site description and default description, also used in jekyll-seo-tag
url: "https://lab41.org" # Site url, also used in jekyll-seo-tag
baseurl: ""
repo: "https://github.com/voices18.github.io"
email: "vsandesara@iqt.org"
# disqus: "alembic-1" # Blog post comments, uncomment the option and set the site ID from your Disqus account
avatarurl: "/assets/speech.ico" # "https://www.gravatar.com/avatar/6c0377abcf4da91cdd35dea4554b2a4c" # Uses avatars for favicons to get multple sites, eg Gravatar, Twitter, GitHub
# google_analytics: ''
# service_worker: false # Will turn off the service worker if set to false
css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference

# 8. Site navigation
navigation_header:
  Home: /
  Downloads: /downloads/
  Events: /blog/
  Reading: /reading/
  Organizers: /organizers/
  Links: /links/
  Search: /search/

navigation_footer:
  A Speech Collaboration: https://voices.github.io

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  Twitter: https://twitter.com/lab41
  # LinkedIn: https://www.linkedin.com/in/daviddarnes
  # Google+: https://plus.google.com/+DavidDarnes
  GitHub: https://github.com/lab41
  link: https://voices18.github.io
  # RSS: /feed.xml

sharing_links: # Appear at the bottom of single blog posts, uncomment and comment out as desired. Colours set the button colour
  Twitter: "#0d94e7"
  facebook: "#3B5998"
  # Google+: "#DC4E41"
  # Pinterest: "#BD081C"
  # LinkedIn: "#0077B5"
  # tumblr: "#36465D"
  Reddit: "#FF4500"
  Hacker News: "#ff6600"
  # Designer News: "#2D72D9"
  Email: "vsandesara@iqt.org"
